### ISSUE TITLE
how to issue wildcard certificate?

### ISSUE THREAD

**Issue by oz42** [bruncsak/ght-acme.sh#10]
How can I get a domain wildcard certificate?

**Comment by bruncsak** [comment]
You can have wildcard certificate only with `DNS-01` challenge (this restriction comes from the ACME specification). The `-l dns-01` flag enables that. With the `-P` flag you can specify a program/script to establish the challenge in the DNS. If you do not specify that flag, the program `nsupdate` will be called. That must be preconfigured on a way that it could perform dynamic DNS update for the zone(s) you require the wildcard certificate.
