### ISSUE TITLE
Add a meaningful User-Agent

### ISSUE THREAD

**Issue by jsha** [bruncsak/ght-acme.sh#2]
AFAICT, this client sends `User-Agent: curl/<version>` by default. Please update it to set a User-Agent string that defines the client name and version. Thanks!

**Comment by bruncsak** [comment]
@jsha , I implemented the meaningful User-Agent feature in the client script:
https://github.com/bruncsak/letsencrypt.sh/commit/0877033d21006b6ee61fbe385cdabde95d278e2a
 I made a test run in the staging environment: https://acme-staging.api.letsencrypt.org . May I ask you to check the staging boulder server log for the string bruncsak/ght-acme.sh ? Please let me know your findings.

**Comment by jsha** [comment]
I confirm that that string shows up in the logs. Could you also make it include the version of your client? Thanks!

**Comment by bruncsak** [comment]
@jsha , I added the version information into the User-Agent string of the client script: https://github.com/bruncsak/letsencrypt.sh/commit/08105f271fadcbfc3653e82e6246b7ffa60090e8
