### ISSUE TITLE
Cannot handle HTTP/2 responses

### ISSUE THREAD

**Issue by C-Otto** [bruncsak/ght-acme.sh#3]
Curl seems to do HTTP/2 requests lately, which breaks the script. Adding `--http1.1` to the curl calls helps, but this feels like a hack.

**Comment by bruncsak** [comment]
Thanks for reporting the problem!
I fixed the code, please let me know if you are still having problem to use a recent version of curl.

**Comment by C-Otto** [comment]
I didn't try your code, but I tried a similar fix. I think the response headers are all lowercase with HTTP/2, which the code does not expect. I'll check when I find the time.

**Comment by alexzorin** [comment]
Yes, on a relatively modern system where curl is linked against nghttp2, the script can't find `location`/`replay-nonce` when they are lower-cased, which is a MUST in HTTP/2 .

For example:

    $ ./letsencrypt.sh register -a account.key -e me@example.com
    register account
    could not fetch new nonce
    unhandled response while registering account

    HTTP/2 400
    server: nginx
    date: Fri, 10 Jan 2020 21:42:50 GMT
    content-type: application/problem+json
    content-length: 114
    cache-control: public, max-age=0, no-cache
    link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
    replay-nonce: 0002EOKsggTfccAWuMjEni91orI0qctSzED0Ncvy1TJ-iiQ

    {
      "type": "urn:ietf:params:acme:error:malformed",
      "detail": "No embedded JWK in JWS header",
      "status": 400
    }

Other shell-based ACME clients made similar fixes a few months ago:

- https://github.com/lukas2511/dehydrated/commit/e4e712c03ad70bd5100af1333c2801f4b5baa89a
- https://github.com/Neilpang/acme.sh/pull/2126

**Comment by bruncsak** [comment]
> Yes, on a relatively modern system where curl is linked against nghttp2, the script can't find `location`/`replay-nonce` when they are lower-cased, which is a MUST in HTTP/2 .

Thank you very much for testing the code. I believe that it is fixed now with the commit https://github.com/bruncsak/ght-acme.sh/commit/8232b73a66b7b89f8c46e212581226c8a51d3ceb.

**Comment by alexzorin** [comment]
Works for me.
