### ISSUE TITLE
How to change duration of certificate?

### ISSUE THREAD

**Issue by contentfree** [bruncsak/ght-acme.sh#8]
Let's Encrypt defaults to 90 days but I believe the API allows for longer. Can ght-acme.sh provide this functionality?

**Comment by bruncsak** [comment]
The validity duration of the certificate issued by the CA is not dependent on the client used, neither on the API of the ACME protocol. It is exclusively up to the issuing CA. For example, Let's Encrypt gives certificate for 3 months. Buypass gives 6 months valid certificate. (`letsencrypt.sh sign -D 'https://api.buypass.com/acme/directory' ...`)
